# Generated by Django 3.1.1 on 2021-01-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockers',
            name='Pro_cate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.product_category'),
        ),
    ]
