# Generated by Django 3.1.7 on 2021-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_lockers_pro_cate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockers',
            name='lock_time',
            field=models.IntegerField(default=None),
        ),
    ]
