# Generated by Django 3.1.7 on 2021-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_lockers_lock_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockers',
            name='mode',
        ),
    ]
