# Generated by Django 3.1.1 on 2020-12-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_departments_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_departments_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('remark', models.TextField(default='')),
                ('AuthUser_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Departments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.departments')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_profiles_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_profiles_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('proposition', models.CharField(default=None, max_length=50)),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_questions_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_questions_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Quest_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('answer', models.CharField(default=None, max_length=50)),
                ('Profiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
                ('Questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questions')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_quest_answers_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_quest_answers_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
