# Generated by Django 3.1.1 on 2020-12-30 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_unit_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_unit_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('code', models.CharField(default=None, max_length=50)),
                ('Departments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.departments')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_product_category_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_product_category_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
