

ui=[{
    'path':'/user001',
    'Profiles_id':'',
    'Features_id':'1',
    'perm_read':True,
    'perm_unlink':False,
    'perm_write':True,
    'perm_create':False
},
{
    'path':'/user002',
    'Profiles_id':'',
    'Features_id':'1',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/inv001',
    'Profiles_id':'',
    'Features_id':'2',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/inv002',
    'Profiles_id':'',
    'Features_id':'2',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/inv003',
    'Profiles_id':'',
    'Features_id':'2',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/dra001',
    'Profiles_id':'',
    'Features_id':'3',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/set001',
    'Profiles_id':'',
    'Features_id':'4',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/set002',
    'Profiles_id':'',
    'Features_id':'4',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/set003',
    'Profiles_id':'',
    'Features_id':'4',
    'perm_read':False,
    'perm_unlink':True,
    'perm_write':True,
    'perm_create':True
},
{
    'path':'/set004',
    'Profiles_id':'',
    'Features_id':'4',
    'perm_read':False,
    'perm_unlink':False,
    'perm_write':False,
    'perm_create':False
},
{
    'path':'/set005',
    'Profiles_id':'',
    'Features_id':'4',
    'perm_read':False,
    'perm_unlink':True,
    'perm_write':True,
    'perm_create':True
},
]