# Generated by Django 3.1.1 on 2020-12-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('locker', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_features_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_features_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='UI_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('path', models.CharField(default=None, max_length=100)),
                ('perm_read', models.BooleanField(default=True)),
                ('perm_unlink', models.BooleanField(default=True)),
                ('perm_write', models.BooleanField(default=True)),
                ('perm_create', models.BooleanField(default=True)),
                ('Features_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.features')),
                ('Profiles_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.profiles')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_ui_access_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_ui_access_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Locker_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('Lockers_ids', models.ManyToManyField(blank=True, to='locker.Lockers')),
                ('Profiles_ids', models.ManyToManyField(blank=True, to='users.Profiles')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_locker_access_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_locker_access_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
