# Generated by Django 3.1.1 on 2021-01-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20210106_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui_access',
            name='Features_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.features'),
        ),
    ]
