# Generated by Django 3.1.7 on 2021-03-01 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0003_ui_access_features_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_functions_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_functions_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.RenameField(
            model_name='ui_access',
            old_name='path',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ui_access',
            name='Features_id',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='ui_access',
            name='Functions_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.functions'),
        ),
    ]
