# Generated by Django 3.1.7 on 2021-03-04 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_lockers_pro_cate_id'),
        ('users', '0001_initial'),
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0004_auto_20210301_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker_access',
            name='Profiles_ids',
        ),
        migrations.AddField(
            model_name='locker_access',
            name='Profiles_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
        ),
        migrations.CreateModel(
            name='category_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('written_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('Lockers_ids', models.ManyToManyField(blank=True, to='locker.Lockers')),
                ('Pro_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.product_category')),
                ('Profiles_ids', models.ManyToManyField(blank=True, to='users.Profiles')),
                ('create_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_category_access_create_uid', to=settings.AUTH_USER_MODEL)),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_category_access_write_uid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
