# Generated by Django 3.1.7 on 2021-03-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20210106_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='value',
            new_name='IP',
        ),
        migrations.AddField(
            model_name='information',
            name='guarantee_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='information',
            name='kind',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='machine_NO',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='manufacture_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='information',
            name='soft_NO',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
